### ISSUE TITLE
能否新增根据相对位置进行保存的功能

### ISSUE THREAD

**Issue by GenesisAN** [JixunMoe/dupan-helper#2]
比如对最后的文件名进行解析:
MD5#MD5#99999#./ABC/xxx.zip
这样在转存储文件的时候设置保存目录为:
/File/
那么这个文件就会被存储在:
/File/ABC/xxx.zip
这样的话，可以人为的在批量发布秒传链接后，下载者可以保留相对的文件夹位置关系

**Comment by jixunmoe** [comment]
现在已经是这样了的吧？

**Comment by GenesisAN** [comment]
干🙄，用：
MD5#MD5#99999#/ABC/xxx.zip
或者：
MD5#MD5#99999#ABC/xxx.zip
都可以，是我孤陋寡闻了😭
