### ISSUE TITLE
使用失败……

### ISSUE THREAD

**Issue by Moryoe** [JixunMoe/dupan-helper#5]
![13DC@ZRBRZXW``ZN$ M@XDS](https://user-images.githubusercontent.com/67630254/86103920-f777e000-baef-11ea-9925-6047060cea9c.png)

**Comment by jixunmoe** [comment]
稍后重试，也有可能百度网盘那边没缓存过来。

**Comment by Moryoe** [comment]
……这个问题我遇到了有几天了，不清楚该怎么处理……




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jixun Wu"<notifications@github.com&gt;; 
发送时间: 2020年6月30日(星期二) 下午5:50
收件人: "JixunMoe/dupan-helper"<dupan-helper@noreply.github.com&gt;; 
抄送: "1953697952"<1953697952@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [JixunMoe/dupan-helper] 使用失败…… (#5)





 
稍后重试，也有可能百度网盘那边没缓存过来。

**Comment by jixunmoe** [comment]
```
855E7B1A30C30612AF4EF48E98ADA278#3DF18E7BF1E05C9E40EA5B6E061FE4D8#295682048#LibreOffice_6.2.4_Win_x64.msi
```

你试试项目主页的这个链接，如果可以的话只能说明：

1. 百度没缓存
   1. 百度缓存了错误的哈希值，需要其他人手动上传一次修复
   2. 再等几天看有没有成功缓存。
2. 浏览器或其它用户脚本兼容问题：
   1. 禁用其他插件/扩展/脚本然后看看能否正常执行
   2. 提供详细的浏览器与用户脚本扩展名称我这边复测

如果不能正常转存：

1. 接口失效，得等人日客户端找到新的接口。
   1. 我这里能正常使用，所以问题与接口应该无关。

**Comment by jingshangyuanyu** [comment]
大佬，我也碰到同样问题了，但是我是连上面的链接也存不了，这个等客户端找到新的接口是要咋整的QAQ

**Comment by Moryoe** [comment]
啊？


&nbsp;


1953697952
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月26日(星期三) 晚上9:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jixunmoe/dupan-helper] 使用失败…… (#5)





 
大佬，我也碰到同样问题了，但是我是连上面的链接也存不了，这个等客户端找到新的接口是要咋整的QAQ

**Comment by jixunmoe** [comment]
> 大佬，我也碰到同样问题了，但是我是连上面的链接也存不了，这个等客户端找到新的接口是要咋整的QAQ

请换用别的脚本：
https://greasyfork.org/scripts/424574
